services:
  rabbitmq:
    image: rabbitmq:4.3-management-alpine
    container_name: nestjs-rabbitmq-demo-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: my-message-queue
      RABBITMQ_DEFAULT_PASS: "123456"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  rabbitmq-data:
